### PR TITLE
Allow several names for the libclang lib

### LINKED ISSUE #20: Could not open library 'clang'
Not sure if this is an issue with ffi-gen or not but when I try and run ffi-gen I get the following error:

```
`block in ffi_lib': Could not open library 'clang': /usr/lib/clang: cannot read file data: Is a directory. (LoadError)
Could not open library 'libclang.so': libclang.so: cannot open shared object file: No such file or directory
```

Mind helping me out? I'm on Ubuntu and installed clang with `apt-get` but not sure what else i need to do to get it working.

Thanks!

### PR DESCRIPTION
**Pull request by mvz**
This fixes #20, allowing `rake test` to run.

Tests are still failing on my machine due to several different problems, mainly missing headers and libraries.

### CODE REVIEW

**Comment by whitequark** [comment]
Superseded by #30.

**Comment by whitequark** [comment]
Fixed in master.

**Comment by mvz** [comment]
@whitequark won't your solution give problems on Mac OSX because the library files are named differently there? I don't run Mac OSX myself so I can't check it.

**Comment by whitequark** [comment]
It should fall back to `clang` in this case.

**Pull request closed without merging**
